#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Student_Management")]
	public partial class dc_student_managementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertStuCou(StuCou instance);
    partial void UpdateStuCou(StuCou instance);
    partial void DeleteStuCou(StuCou instance);
    partial void InsertCourse(Course instance);
    partial void UpdateCourse(Course instance);
    partial void DeleteCourse(Course instance);
    #endregion
		
		public dc_student_managementDataContext() : 
				base(global::Student_Management.Properties.Settings.Default.Student_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dc_student_managementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dc_student_managementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dc_student_managementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dc_student_managementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Student> Student
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<StuCou> StuCou
		{
			get
			{
				return this.GetTable<StuCou>();
			}
		}
		
		public System.Data.Linq.Table<Course> Course
		{
			get
			{
				return this.GetTable<Course>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StuNo;
		
		private System.Nullable<int> _ClassNo;
		
		private string _StuName;
		
		private string _Sex;
		
		private System.Nullable<System.DateTime> _BirthDay;
		
		private string _Pwd;
		
		private EntitySet<StuCou> _StuCou;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStuNoChanging(string value);
    partial void OnStuNoChanged();
    partial void OnClassNoChanging(System.Nullable<int> value);
    partial void OnClassNoChanged();
    partial void OnStuNameChanging(string value);
    partial void OnStuNameChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnBirthDayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDayChanged();
    partial void OnPwdChanging(string value);
    partial void OnPwdChanged();
    #endregion
		
		public Student()
		{
			this._StuCou = new EntitySet<StuCou>(new Action<StuCou>(this.attach_StuCou), new Action<StuCou>(this.detach_StuCou));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuNo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StuNo
		{
			get
			{
				return this._StuNo;
			}
			set
			{
				if ((this._StuNo != value))
				{
					this.OnStuNoChanging(value);
					this.SendPropertyChanging();
					this._StuNo = value;
					this.SendPropertyChanged("StuNo");
					this.OnStuNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassNo", DbType="Int")]
		public System.Nullable<int> ClassNo
		{
			get
			{
				return this._ClassNo;
			}
			set
			{
				if ((this._ClassNo != value))
				{
					this.OnClassNoChanging(value);
					this.SendPropertyChanging();
					this._ClassNo = value;
					this.SendPropertyChanged("ClassNo");
					this.OnClassNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StuName
		{
			get
			{
				return this._StuName;
			}
			set
			{
				if ((this._StuName != value))
				{
					this.OnStuNameChanging(value);
					this.SendPropertyChanging();
					this._StuName = value;
					this.SendPropertyChanged("StuName");
					this.OnStuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="VarChar(50)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDay", DbType="Date")]
		public System.Nullable<System.DateTime> BirthDay
		{
			get
			{
				return this._BirthDay;
			}
			set
			{
				if ((this._BirthDay != value))
				{
					this.OnBirthDayChanging(value);
					this.SendPropertyChanging();
					this._BirthDay = value;
					this.SendPropertyChanged("BirthDay");
					this.OnBirthDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pwd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pwd
		{
			get
			{
				return this._Pwd;
			}
			set
			{
				if ((this._Pwd != value))
				{
					this.OnPwdChanging(value);
					this.SendPropertyChanging();
					this._Pwd = value;
					this.SendPropertyChanged("Pwd");
					this.OnPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StuCou", Storage="_StuCou", ThisKey="StuNo", OtherKey="StuNo")]
		public EntitySet<StuCou> StuCou
		{
			get
			{
				return this._StuCou;
			}
			set
			{
				this._StuCou.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StuCou(StuCou entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_StuCou(StuCou entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StuCou")]
	public partial class StuCou : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StuNo;
		
		private int _CouNo;
		
		private System.Nullable<int> _Grade;
		
		private EntityRef<Student> _Student;
		
		private EntityRef<Course> _Course;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStuNoChanging(string value);
    partial void OnStuNoChanged();
    partial void OnCouNoChanging(int value);
    partial void OnCouNoChanged();
    partial void OnGradeChanging(System.Nullable<int> value);
    partial void OnGradeChanged();
    #endregion
		
		public StuCou()
		{
			this._Student = default(EntityRef<Student>);
			this._Course = default(EntityRef<Course>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuNo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StuNo
		{
			get
			{
				return this._StuNo;
			}
			set
			{
				if ((this._StuNo != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStuNoChanging(value);
					this.SendPropertyChanging();
					this._StuNo = value;
					this.SendPropertyChanged("StuNo");
					this.OnStuNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CouNo
		{
			get
			{
				return this._CouNo;
			}
			set
			{
				if ((this._CouNo != value))
				{
					if (this._Course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCouNoChanging(value);
					this.SendPropertyChanging();
					this._CouNo = value;
					this.SendPropertyChanged("CouNo");
					this.OnCouNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int")]
		public System.Nullable<int> Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StuCou", Storage="_Student", ThisKey="StuNo", OtherKey="StuNo", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.StuCou.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.StuCou.Add(this);
						this._StuNo = value.StuNo;
					}
					else
					{
						this._StuNo = default(string);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_StuCou", Storage="_Course", ThisKey="CouNo", OtherKey="CouNo", IsForeignKey=true)]
		public Course Course
		{
			get
			{
				return this._Course.Entity;
			}
			set
			{
				Course previousValue = this._Course.Entity;
				if (((previousValue != value) 
							|| (this._Course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Course.Entity = null;
						previousValue.StuCou.Remove(this);
					}
					this._Course.Entity = value;
					if ((value != null))
					{
						value.StuCou.Add(this);
						this._CouNo = value.CouNo;
					}
					else
					{
						this._CouNo = default(int);
					}
					this.SendPropertyChanged("Course");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course")]
	public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CouNo;
		
		private string _CouName;
		
		private float _Credit;
		
		private EntitySet<StuCou> _StuCou;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCouNoChanging(int value);
    partial void OnCouNoChanged();
    partial void OnCouNameChanging(string value);
    partial void OnCouNameChanged();
    partial void OnCreditChanging(float value);
    partial void OnCreditChanged();
    #endregion
		
		public Course()
		{
			this._StuCou = new EntitySet<StuCou>(new Action<StuCou>(this.attach_StuCou), new Action<StuCou>(this.detach_StuCou));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CouNo
		{
			get
			{
				return this._CouNo;
			}
			set
			{
				if ((this._CouNo != value))
				{
					this.OnCouNoChanging(value);
					this.SendPropertyChanging();
					this._CouNo = value;
					this.SendPropertyChanged("CouNo");
					this.OnCouNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouName", DbType="VarChar(50)")]
		public string CouName
		{
			get
			{
				return this._CouName;
			}
			set
			{
				if ((this._CouName != value))
				{
					this.OnCouNameChanging(value);
					this.SendPropertyChanging();
					this._CouName = value;
					this.SendPropertyChanged("CouName");
					this.OnCouNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Credit", DbType="Real NOT NULL")]
		public float Credit
		{
			get
			{
				return this._Credit;
			}
			set
			{
				if ((this._Credit != value))
				{
					this.OnCreditChanging(value);
					this.SendPropertyChanging();
					this._Credit = value;
					this.SendPropertyChanged("Credit");
					this.OnCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_StuCou", Storage="_StuCou", ThisKey="CouNo", OtherKey="CouNo")]
		public EntitySet<StuCou> StuCou
		{
			get
			{
				return this._StuCou;
			}
			set
			{
				this._StuCou.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StuCou(StuCou entity)
		{
			this.SendPropertyChanging();
			entity.Course = this;
		}
		
		private void detach_StuCou(StuCou entity)
		{
			this.SendPropertyChanging();
			entity.Course = null;
		}
	}
}
#pragma warning restore 1591
